<h1 align="center">Phát hiện Fake News với Python</h1>

Trong thời đại bùng nổ thông tin và sự phát triển nhanh chóng của các mạng xã hội, việc đối mặt với đợt sóng "Fake News" - hay tin đồn giả mạo, đang trở thành một thách thức ngày càng lớn đối với mức độ đáng tin cậy của thông tin. Điều này không chỉ đặt ra thách thức về quản lý thông tin mà còn đe dọa đến sự ổn định của nền kinh tế tri thức và tự do ngôn luận. Trong bối cảnh như vậy, việc phát triển một mô hình nhằm cải thiện khả năng lọc thông tin chính xác đóng vai trò hết sức quan trọng trong việc ngăn chặn thông tin giả mạo. Vậy có cách nào để làm được việc đấy không? Câu trả lời là có. Sau đây, chúng tôi sẽ giới thiệu đến mọi người mô hình <b>"Phát hiện Fake News với Python".</b>

### <b>Tập dữ liệu</b>
Tập dữ liệu được sử dụng trong mô hình có tên là <code>news.csv</code> (nguồn: <code>train.csv</code> từ <a href="https://www.kaggle.com/c/fake-news/data">Kaggle</a>, có thêm bớt vài nghìn bài báo), trong đó có các đề mục là:
- id: mã định danh duy nhất cho mỗi bài báo
- title: tiêu đề của bài báo
- author: tác giả của bài báo
- text: nội dung của bài báo, có thể không đầy đủ
- label: một nhãn để đánh dấu bài báo có thể không đáng tin cậy
    - 1: không đáng tin cậy - tin chưa chuẩn - FAKE
    - 0: đáng tin cậy - tin chuẩn - REAL

### <b>Xây dựng mô hình</b>

#### 1. Import các thư viện cần thiết

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

#### 2. Đọc dữ liệu vào DataFrame

In [2]:
# Đọc dữ liệu vào dataframe
df = pd.read_csv("./news.csv")
# Xem kích thước và 5 dòng đầu của dữ liệu
print("Shape:", df.shape)
df.head(5)

Shape: (21300, 5)

,id,title,author,text,label
0,0,"After F.B.I.’s Inquiry Into Omar Mateen, a Foc...",Matt Apuzzo and Eric Lichtblau,"WASHINGTON — Every day, in F. B. I. offices...",0
1,1,George Mason Univ. Gets Their Fascism On – Who...,Terresa Monroe-Hamilton,George Mason Univ. Gets Their Fascism On – W...,1
2,2,Milo: Free Speech Is ’Under Threat’ on College...,Trent Baker,Following the violent protest at earlier thi...,0
3,3,JUDGMENT DAY: The One Reason Why Every Christi...,Geoffrey Grider,JUDGMENT DAY: The One Reason Why Every Chris...,1
4,4,"Azed crossword 2,684",Guardian staff,NaN,0

#### 3. Thay đổi và lấy các nhãn của DataFrame

In [3]:
# Thay đổi các nhãn của dataframe
df["label"] = df["label"].astype("object")
df.loc[(df["label"] == 1), ["label"]] = "FAKE"
df.loc[(df["label"] == 0), ["label"]] = "REAL"

In [4]:
# Xem lại 5 dòng đầu của dữ liệu
df.head(5)

,id,title,author,text,label
0,0,"After F.B.I.’s Inquiry Into Omar Mateen, a Foc...",Matt Apuzzo and Eric Lichtblau,"WASHINGTON — Every day, in F. B. I. offices...",REAL
1,1,George Mason Univ. Gets Their Fascism On – Who...,Terresa Monroe-Hamilton,George Mason Univ. Gets Their Fascism On – W...,FAKE
2,2,Milo: Free Speech Is ’Under Threat’ on College...,Trent Baker,Following the violent protest at earlier thi...,REAL
3,3,JUDGMENT DAY: The One Reason Why Every Christi...,Geoffrey Grider,JUDGMENT DAY: The One Reason Why Every Chris...,FAKE
4,4,"Azed crossword 2,684",Guardian staff,NaN,REAL

In [5]:
# Lấy các nhãn từ dataframe
labels = df.label
labels.head(5)

0    REAL
1    FAKE
2    REAL
3    FAKE
4    REAL
Name: label, dtype: object

#### 4. Chia bộ dữ liệu thành các tập train và test

In [6]:
# Trộn tiêu đề, tác giả và nội dung
df["combined_info"] = df.apply(
    lambda row: f"Title: {row['title']}\nAuthors: {row['author']}\nText:\n{row['text']}",
    axis=1,
)

# Chia bộ dữ liệu
x_train, x_test, y_train, y_test = train_test_split(
    df["combined_info"], labels, test_size=0.2, random_state=7
)

#### 5. Khởi tạo TfidfVectorizer và thực hiện lắp đặt, biến đổi

In [7]:
# Khởi tạo TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words="english", max_df=0.7)

# Lắp đặt và biến đổi tập train; biến đổi tập test
tfidf_train = tfidf_vectorizer.fit_transform(x_train)
tfidf_test = tfidf_vectorizer.transform(x_test)

#### 6. Khởi tạo PassiveAggressionClassifier và thực hiện dự đoán

In [8]:
# Khởi tạo PassiveAggressiveClassifier
pac = PassiveAggressiveClassifier(max_iter=50)
pac.fit(tfidf_train, y_train)

# Dự đoán trên tập test và tính toán độ chính xác
y_pred = pac.predict(tfidf_test)
score = accuracy_score(y_test, y_pred)
print(f"Accuracy: {round(score*100,2)}%")

Accuracy: 95.66%

#### 7. In ra ma trận hỗn loạn

In [9]:
# Xây dựng ma trận hỗn loạn
cm = confusion_matrix(y_test, y_pred, labels=["FAKE", "REAL"])
cm_df = pd.DataFrame(
    cm, index=["True_FAKE", "True_REAL"], columns=["Pred_FAKE", "Pred_REAL"]
)
cm_df

           Pred_FAKE  Pred_REAL
True_FAKE       2023         85
True_REAL        100       2052

#### 8. Thực hiện dự đoán với nội dung được nhập vào

In [10]:
from newspaper import Article

def input_info(title, authors, text):
    return f"Title: {title}\nAuthors: {', '.join(authors)}\nText:\n{text}"


url = input("Nhập url của bài báo")
article = Article(url)
article.download()
article.parse()

text_input = input_info(article.title, article.authors, article.text)

text_tfidf = tfidf_vectorizer.transform([text_input])
label_pred = pac.predict(text_tfidf)
print(f"Kết quả dự đoán: {label_pred}")

print(" ".join(text_input.split(" ")[:100]) + " ...")

Kết quả dự đoán: ['REAL']
Title: Ten Hag takes blame for Man United squandering another lead
Authors:
Text:
Manchester United manager Erik ten Hag at the Champions League game between Galatasaray and Manchester United at RAMS Park, Istanbul, Turkey, Nov. 29, 2023. Photo by Reuters/Umit Bektas

Manchester United manager Erik ten Hag said he was responsible for his side throwing away yet another lead in the Champions League after they were pegged back to a 3-3 draw with Galatasaray on Wednesday.

The three-time European champions blew a two-goal lead twice in Istanbul, with goalkeeper Andre Onana making two costly errors, to leave their hopes of reaching the last 16 ...