#### 1. Import các thư viện cần thiết

Các thư viện bao gồm numpy, pandas và sklearn.
Do tập dữ liệu đầu vào của chúng ta là dạng văn bản(text) cho nên chúng ta cần phải đưa về một dạng dữ diệu có thể sử dụng được trong quan điểm của Machine Learing. Ở đây, chúng ta sẽ sử dụng cách véc tơ hóa để biến đổi dữ liệu từ text thành mảng hoặc một dạng dữ liệu tương đương với véc tơ.

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

#### 2. Đọc dữ liệu vào DataFrame

Ở bước kế tiếp sau khi đã có được các thư viện cần thiết. Chúng ta sẽ bắt đầu làm việc với nó, đầu tiên là thực hiện các lệnh đọc và in ra dữ liệu theo cách dưới đây:

In [2]:
# Đọc dữ liệu vào dataframe
df = pd.read_csv("./news.csv")
# Xem kích thước và 5 dòng đầu của dữ liệu
print("Shape:", df.shape)
df.head(5)

Shape: (20800, 5)

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

Dữ liệu của chúng ta sẽ bao gồm id, tiêu đề(title), tác giả(author), nội dung(text), và nhãn đánh dấu fake hoặc real (label).
Trong đó nhãn đánh đấu của chúng ta sẽ bao gồm 0 và 1 với nhãn 0 là tin chuẩn (real) và nhãn 1 là tin chưa chuẩn (fake).

#### 3. Thay đổi và lấy các nhãn của DataFrame

Kế đến, sau khi đã làm việc với dữ liệu một cách chuẩn chỉ với id, title, author và label thì chúng ta sẽ thực hiện bước cho label hiển thị trực tiếp "REAL" hoặc "FAKE" thay vì 0 hoặc 1. Vì nếu như chúng ta để nguyên label là 0 hoặc 1 thì có thể người sử dụng sẽ không phân biệt được đâu là REAL hoặc FAKE vì các họ không biết 0 và 1 cái nào là REAL cái nào là FAKE. Nếu giữ 0 và 1 làm output thì phải chú thích cho người dùng hiểu được thông qua một cách nhắc nhở nào đó, điều này rất bất tiện. Do đó, việc thay đổi label là cần thiết.

In [3]:
# Thay đổi các nhãn của dataframe
df["label"] = df["label"].astype("object")
df.loc[(df["label"] == 1), ["label"]] = "FAKE"
df.loc[(df["label"] == 0), ["label"]] = "REAL"

In [4]:
# Xem lại 5 dòng đầu của dữ liệu
df.head(5)

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,FAKE
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,REAL
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",FAKE
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,FAKE
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,FAKE

Ta có thể thấy, label đã được thay đổi output thành REAL hoặc FAKE thuận tiện hơn trong việc sử dụng

Nếu như chỉ muốn xem tin chuẩn hay không chuẩn mà không quan tâm đến nội dung hay tác giả, ta có thể thực hiện như sau:

In [5]:
# Lấy các nhãn từ dataframe
labels = df.label
labels.head(5)

0    FAKE
1    REAL
2    FAKE
3    FAKE
4    FAKE
Name: label, dtype: object

#### 4. Chia bộ dữ liệu thành các tập train và test

In [1]:
# Trộn tiêu đề, tác giả và nội dung
df["combined_info"] = df.apply(
    lambda row: f"Title: {row['title']}\nAuthors: {row['author']}\nText:\n{row['text']}",
    axis=1,
)

# Chia bộ dữ liệu
x_train, x_test, y_train, y_test = train_test_split(
    df["combined_info"], labels, test_size=0.2, random_state=7
)

NameError: name 'df' is not defined